### ISSUE TITLE
 undefined reference to `uuid_generate'

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#458] opened 2017-03-28 21:42 UTC
Hi
I have a problem in another machin I am testing in ubuntu 14.4.
please find the log attached when running ./build.sh
[log.txt](https://github.com/kind2-mc/kind2/files/877144/log.txt)

**Comment by daniel-larraz** [comment] 2017-03-29 00:34
Hi Hamza,

I am not sure why you are getting that error message.

The following steps worked for me on a fresh installation of Ubuntu 14.04.5 (x86_64):

    # Installation of lastest ocaml distribution with opam:
    ## Get the latest opam binary from https://github.com/ocaml/opam/releases/latest
    ## Then execute:
    ./opam-<version> init --comp=4.04.0
    ./opam-<version> install menhir

    # Make sure Ocaml 4.04.0 is in your path:
    ocaml -version

    # Installation of other requirements:
    sudo apt-get install automake libtool g++ git

    git clone https://github.com/kind2-mc/kind2.git

    cd kind2
    ./autogen.sh
    ./build.sh --prefix=<path>

I hope the above will be useful to you.

Best,
Daniel

**Comment by arthaud** [comment] 2017-03-29 00:36
I had the same issue. For information, it builds if I replace:
```
OCAMLBUILD=@OCAMLBUILD@ -j 0 -cflags -w,@P@U@F
```
by
```
OCAMLBUILD=@OCAMLBUILD@ -j 0 -cflags -w,@P@U@F -lflags="-cclib -luuid"
```
in **src/Makefile.in**
This is very hacky though.

**Comment by arthaud** [comment] 2017-03-29 20:22
The problem is that **czmq** uses **libuuid** to implement their zuuid type. If **libuuid** is not found on the system, they have a [home made implementation](https://github.com/kind2-mc/kind2/blob/develop/ocamlczmq/czmq/src/zuuid.c)

If libuuid was found by czmq, you have to link kind2 with the `-luuid` flag.

I see two solutions:
* Find out if **czmq** used **libuuid**, and in that case, add the flag **-luuid**.
* Tell **czmq** not to use **libuuid**. Apparently we could use the **--with-uuid=no** when running ./configure

**Comment by arthaud** [comment] 2017-03-29 20:54
Apparently, the embedded czmq does not take into account `--with-uuid=no` if **libuuid** was found by **pkg-config** (see [here](https://github.com/kind2-mc/kind2/blob/develop/ocamlczmq/czmq/configure.ac#L125)), so the second solution doesn't work. FYI, it is fixed in the [latest version of czmq](https://github.com/zeromq/czmq/blob/master/configure.ac#L186).

**Comment by daniel-larraz** [comment] 2017-03-30 14:57
Hi,

Maxime: thank you very much for your comments.

I have [disabled](https://github.com/kind2-mc/kind2/pull/459) the use of the uuid library.

Hamza: could you update your local repo with the fix, and check if everything works now?

Thank you,
Daniel

**Comment by arthaud** [comment] 2017-03-30 20:55
I just tried it on a machine that has **libuuid** and it works perfectly.
@hbourbouh  told me he fixed the issue using my hack.

Thank you @daniel-larraz

**Closed** 2017-03-30 20:57 UTC
Labels: bug
